# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4404f2cf0be73c304b000d5f58ecd7571a33d8fac0b33cb77c9d2e9cc3fe30487ae5a276ab4b0bf04c48da8c4e0881de262471cc62a0fa16516cf092e813344

test:
  secret_key_base: 4434deaa64455e9307189b6fe777493c439cb496482f55d901f52668bd8d691d946285c6fef504ffa58a2594a59beec56ae3b9e9227a4d34023776a8736ab873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
